Sender: LSF System <lsfadmin@eu-ms-011-25>
Subject: Job 131019337: <python3 rbergomi_dnn_m1.py> in cluster <euler> Exited

Job <python3 rbergomi_dnn_m1.py> was submitted from host <eu-login-29> by user <robinvo> in cluster <euler> at Mon Jul 13 15:07:50 2020
Job was executed on host(s) <eu-ms-011-25>, in queue <normal.24h>, as user <robinvo> in cluster <euler> at Mon Jul 13 15:08:14 2020
</cluster/home/robinvo> was used as the home directory.
</cluster/home/robinvo/rv_bachelor_thesis/Rough_Bergomi_Experiments> was used as the working directory.
Started at Mon Jul 13 15:08:14 2020
Terminated at Mon Jul 13 16:56:51 2020
Results reported at Mon Jul 13 16:56:51 2020

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python3 rbergomi_dnn_m1.py
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   6518.05 sec.
    Max Memory :                                 714 MB
    Average Memory :                             592.03 MB
    Total Requested Memory :                     1024.00 MB
    Delta Memory :                               310.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                15
    Run time :                                   6545 sec.
    Turnaround time :                            6541 sec.

The output (if any) follows:

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
0 	RMSE: 0.269616
1 	RMSE: 0.249221
2 	RMSE: 0.253979
3 	RMSE: 0.268959
4 	RMSE: 0.241118
5 	RMSE: 0.251149
6 	RMSE: 0.242813
7 	RMSE: 0.23871
8 	RMSE: 0.264481
9 	RMSE: 0.263971
10 	RMSE: 0.257796
11 	RMSE: 0.247874
12 	RMSE: 0.248369
13 	RMSE: 0.236951
14 	RMSE: 0.228548
15 	RMSE: 0.238197
16 	RMSE: 0.215573
17 	RMSE: 0.212431
18 	RMSE: 0.235533
19 	RMSE: 0.238456
20 	RMSE: 0.222
21 	RMSE: 0.235268
22 	RMSE: 0.23552
23 	RMSE: 0.216102
24 	RMSE: 0.214847
25 	RMSE: 0.23557
26 	RMSE: 0.197511
27 	RMSE: 0.204974
28 	RMSE: 0.220292
29 	RMSE: 0.191328
30 	RMSE: 0.231404
31 	RMSE: 0.215922
32 	RMSE: 0.201083
33 	RMSE: 0.22219
34 	RMSE: 0.219567
35 	RMSE: 0.211045
36 	RMSE: 0.210576
37 	RMSE: 0.220511
38 	RMSE: 0.17815
39 	RMSE: 0.216538
40 	RMSE: 0.193171
41 	RMSE: 0.164422
42 	RMSE: 0.211941
43 	RMSE: 0.177107
44 	RMSE: 0.188897
45 	RMSE: 0.197715
46 	RMSE: 0.186886
47 	RMSE: 0.193912
48 	RMSE: 0.18177
49 	RMSE: 0.18148
50 	RMSE: 0.170025
51 	RMSE: 0.203652
52 	RMSE: 0.176351
53 	RMSE: 0.19219
54 	RMSE: 0.190077
55 	RMSE: 0.178996
56 	RMSE: 0.156682
57 	RMSE: 0.180304
58 	RMSE: 0.144535
59 	RMSE: 0.170858
60 	RMSE: 0.15706
61 	RMSE: 0.175756
62 	RMSE: 0.16263
63 	RMSE: 0.155479
64 	RMSE: 0.157468
65 	RMSE: 0.135441
66 	RMSE: 0.140482
67 	RMSE: 0.14353
68 	RMSE: 0.12658
69 	RMSE: 0.160619
70 	RMSE: 0.148673
71 	RMSE: 0.153046
72 	RMSE: 0.139867
73 	RMSE: 0.142702
74 	RMSE: 0.128763
75 	RMSE: 0.12286
76 	RMSE: 0.132931
77 	RMSE: 0.131577
78 	RMSE: 0.134615
79 	RMSE: 0.120491
80 	RMSE: 0.113439
81 	RMSE: 0.121886
82 	RMSE: 0.106332
83 	RMSE: 0.106995
84 	RMSE: 0.120269
85 	RMSE: 0.103479
86 	RMSE: 0.105381
87 	RMSE: 0.117351
88 	RMSE: 0.111051
89 	RMSE: 0.106736
90 	RMSE: 0.0987174
91 	RMSE: 0.0972678
92 	RMSE: 0.111738
93 	RMSE: 0.100331
94 	RMSE: 0.0959077
95 	RMSE: 0.0919774
96 	RMSE: 0.0895427
97 	RMSE: 0.0846689
98 	RMSE: 0.0791456
99 	RMSE: 0.0880499
100 	RMSE: 0.0924427
101 	RMSE: 0.083172
102 	RMSE: 0.0763006
103 	RMSE: 0.0784563
104 	RMSE: 0.08605
105 	RMSE: 0.0837807
106 	RMSE: 0.0916595
107 	RMSE: 0.0801192
108 	RMSE: 0.0721657
109 	RMSE: 0.0847122
110 	RMSE: 0.0693748
111 	RMSE: 0.0708337
112 	RMSE: 0.064933
113 	RMSE: 0.0774637
114 	RMSE: 0.0666315
115 	RMSE: 0.06558
116 	RMSE: 0.0665257
117 	RMSE: 0.0599764
118 	RMSE: 0.0659508
119 	RMSE: 0.0597554
120 	RMSE: 0.0615372
121 	RMSE: 0.0609292
122 	RMSE: 0.0551164
123 	RMSE: 0.0569588
124 	RMSE: 0.0548669
125 	RMSE: 0.067455
126 	RMSE: 0.0504325
127 	RMSE: 0.0554096
128 	RMSE: 0.0547936
129 	RMSE: 0.0425395
130 	RMSE: 0.0468335
131 	RMSE: 0.0558066
132 	RMSE: 0.0471403
133 	RMSE: 0.0477711
134 	RMSE: 0.0440615
135 	RMSE: 0.046787
136 	RMSE: 0.0492664
137 	RMSE: 0.0404238
138 	RMSE: 0.044406
139 	RMSE: 0.045411
140 	RMSE: 0.0396681
141 	RMSE: 0.0472793
142 	RMSE: 0.0476413
143 	RMSE: 0.0404148
144 	RMSE: 0.0364943
145 	RMSE: 0.0388893
146 	RMSE: 0.045273
147 	RMSE: 0.0433543
148 	RMSE: 0.037947
149 	RMSE: 0.0383721
150 	RMSE: 0.0378436
151 	RMSE: 0.0401148
152 	RMSE: 0.0376051
153 	RMSE: 0.0414832
154 	RMSE: 0.0376775
155 	RMSE: 0.044445
156 	RMSE: 0.0312921
157 	RMSE: 0.0379425
158 	RMSE: 0.0342034
159 	RMSE: 0.0428141
160 	RMSE: 0.0430825
161 	RMSE: 0.0353934
162 	RMSE: 0.0382398
163 	RMSE: 0.0357066
164 	RMSE: 0.03132
165 	RMSE: 0.0330478
166 	RMSE: 0.0284141
167 	RMSE: 0.0350418
168 	RMSE: 0.0353138
169 	RMSE: 0.0361942
170 	RMSE: 0.0336576
171 	RMSE: 0.0286572
172 	RMSE: 0.0346778
173 	RMSE: 0.0357144
174 	RMSE: 0.0308248
175 	RMSE: 0.0317804
176 	RMSE: 0.0268616
177 	RMSE: 0.0302561
178 	RMSE: 0.0333477
179 	RMSE: 0.0342331
180 	RMSE: 0.0293845
181 	RMSE: 0.0291415
182 	RMSE: 0.0267698
183 	RMSE: 0.0324596
184 	RMSE: 0.0324765
185 	RMSE: 0.0336106
186 	RMSE: 0.0307969
187 	RMSE: 0.0285475
188 	RMSE: 0.0283616
189 	RMSE: 0.0346099
190 	RMSE: 0.0319636
191 	RMSE: 0.0303252
192 	RMSE: 0.0291097
193 	RMSE: 0.030853
194 	RMSE: 0.0253021
195 	RMSE: 0.0244396
196 	RMSE: 0.0302187
197 	RMSE: 0.0321314
198 	RMSE: 0.0301785
199 	RMSE: 0.0278224
Traceback (most recent call last):
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
	 [[Node: save/RestoreV2_25 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_25/tensor_names, save/RestoreV2_25/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rbergomi_dnn_m1.py", line 316, in <module>
    thetas_pred[i,:] = predict_theta(implied_vols_surface(thetas_true[i,:]).flatten())
  File "rbergomi_dnn_m1.py", line 295, in predict_theta
    saver.restore(sess, "./models/rBergomi_dnn_m1x")    
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
	 [[Node: save/RestoreV2_25 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_25/tensor_names, save/RestoreV2_25/shape_and_slices)]]

Caused by op 'save/RestoreV2_25', defined at:
  File "rbergomi_dnn_m1.py", line 234, in <module>
    saver = tf.train.Saver()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/rBergomi_dnn_m1x
	 [[Node: save/RestoreV2_25 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_25/tensor_names, save/RestoreV2_25/shape_and_slices)]]

